request_sync:
  description: Send a request_sync command to Maika.
  fields:
    agent_user_id:
      description: "Optional. Only needed for automations. Specific Home Assistant user id (not username, ID in configuration > users > under username) to sync with Maika Assistant. Do not need when you call this service through Home Assistant front end or API. Used in automation script or other place where context.user_id is missing."
